### ISSUE TITLE
Validator doesn't respect server paths

### ISSUE THREAD

**Issue by jschirrmacher** [RuntimeTools/chai-openapi-response-validator#17]
**Describe the bug**
The Validator ignores paths specified in the OAS3 `servers` section.

**To Reproduce**
1. Take a OAS3 file like:
```
openapi: 3.0.0
info:
  title: groundcontrol
  version: "0.1"
  description: test
servers:
  - url: /api
    description: local
paths:
  /monitors:
    get:
      description: get list of monitors
      responses:
        "200":
          description: Retrieved monitor definitions
          content:
            application/json: {}
```
2. Use it as the specification for a test.
3. Let the test check `GET /api/monitors`

Currently, I get an error `Error: No '/api/monitors' path defined in OpenAPI spec`.

**Expected behavior**
The test should work.

**Comment by rwalle61** [comment]
Thanks for raising this! Apologies for the delayed reply.

I believe the fix is to add to the function at https://github.com/RuntimeTools/chai-openapi-response-validator/blob/master/lib/resValidator.js#L113, which tries to match the `res.req.path` to `paths` in the Open API spec. I would write a new function and call it from there. The new function would, for each `path`, combine each `servers` url with the `path`. That should respect these cases and resolve this issue.

I have a busy fortnight ahead so it will be 1 or 2 weekends before I can PR this properly (with tests etc). If you'd like the fix quicker, feel free to raise a PR yourself :)

**Comment by JonnySpruce** [comment]
I'm happy to pick this one up. I'll aim to get a PR done in the next couple of days.

**Comment by JonnySpruce** [comment]
So I've done the required work to do this in OpenAPI 3, however we need to consider how this would work for OpenAPI 2, since multiple servers are not supported. Our tests currently try to test both OpenAPI 3 & 2 docs in the same way so we need to think about how this would work with the servers included.

**Comment by rwalle61** [comment]
Thanks Jonny, and that's a good point. I think supporting a single server would solve this issue, and we could still test OA2 and 3 in the same way. I agree we should in future support multiple servers, and in general decouple tests for OA2 and 3, because they have slightly different function. Could raise an issue for that

If you agree and want to raise a PR supporting a single server, I can review it?

**Comment by JonnySpruce** [comment]
I've now raised a PR to resolve this issue and add testing for it: https://github.com/RuntimeTools/chai-openapi-response-validator/pull/19

**Comment by rwalle61** [comment]
Great work @JonnySpruce! @jschirrmacher could you please verify if this has fixed your problem, and close if so?

**Comment by rwalle61** [comment]
fyi `0.2.5` handles relative `server` paths (in OpenAPI 3 specs) such as `/api`. But it's a further piece of work to handle more variants, such as those listed here https://swagger.io/docs/specification/api-host-and-base-path/

**Comment by jschirrmacher** [comment]
Yes, this works for me, thanks!

**Comment by GSDTN** [comment]
I just saw this now after creating my issue.  I would suggest that the servers as defined in the example above are not servers, but rather paths or base paths.  Servers for the purpose of the spec include protocol, host and domain e.g. https://myapi.mycompany.com.
It is possible that this fix - is what is breaking my tests.
If a full server value is put in, it allows tools such as SwaggerHub to have an Execute section and actually execute the API against the selected server.  Just having /api does not.

**Comment by rwalle61** [comment]
Thanks @GSDTN, will take that into account in https://github.com/RuntimeTools/chai-openapi-response-validator/issues/30
