### ISSUE TITLE
Ability to define API Specs as URL instead of path

### ISSUE THREAD

**Issue by GSDTN** [RuntimeTools/chai-openapi-response-validator#31]
**OpenAPI version**
3

I have my API Specs on an AWS S3 bucket.  As the specs are updates, they are pushed to the bucket.  I would like to have automated testing that compares the API responses to the API Specs.
It would be great if I could pass in the URL of the Spec instead of having to pass in file location.

My current approach is to download the spec and write it to file first and then pass in the path.

**Comment by rwalle61** [comment]
Great idea, sounds like a good improvement for a simple code change.

I may have time next week, or am happy to review a PR that you/someone submit :)

**Comment by rwalle61** [comment]
Probably the most complicated thing about this is whether the request to a URL will be async, and if so how best to manage it

**Comment by rwalle61** [comment]
Correct me if I'm wrong, but I think the simplest way to automatically "download the spec and write it to file first and then pass in the path" is to add, to your existing code, something like:
```js
const syncRequest = require('sync-request');
const fs = require('fs-extra');

// const pathToApiSpec = './foo';
fs.writeFileSync(pathToApiSpec, syncRequest('url/to/openapi/spec').body);
// chai.use(chaiResponseValidator(pathToApiSpec));
```

Alternatively, you could make an async request using a `before` block:
```js
before(async() => {
    const apiSpec = (await axios.get('url/to/openapi/spec')).data;
    fs.writeFileSync(pathToApiSpec, apiSpec);
    // chai.use(chaiResponseValidator(pathToApiSpec));
}
```

With that in mind, I see 3 options:
1. Implement this using a package that can make *sync* requests (e.g. [sync-request](https://www.npmjs.com/package/sync-request)). But this adds complications since the request will not always succeed
2. Implement this using a package that can make *async* requests. But this adds complications since the request will not always succeed, and we will have to load this chai-openapi-response-validator module using [some pattern](https://stackoverflow.com/questions/20238829/asynchronous-nodejs-module-exports) less simple than the current sync loading pattern (just `require`).
3. Don't implement this, and force the user to add the code patterns described above

**Comment by GSDTN** [comment]
That is pretty much what I am doing at the moment, although I was simply using await axios.get instead of syncRequest.

**Comment by rwalle61** [comment]
Okay. Of the 3 ways I've listed above to resolve this issue, I think 1 is best, 3 okay, and 2 very bad for users.

So I'm happy to look at implementing 1

**Comment by GSDTN** [comment]
Another option is to not write to a file at all.  At one point I did some work around and edits to the code to fix my issue.  I made an sync axios.get to get the spec content and passed the content into chaiResponseValidator.  Than I did the following in this function:
```
function loadFile(filepath) {
//  if (!path.isAbsolute(filepath)) {
 //   throw new Error('The "path" argument must be an absolute filepath');
 // }
  //const fileData = fs.readFileSync(filepath);
  try {
    return yaml.safeLoad(filepath);
  } catch (error) {
    throw new Error(`Unable to read the specified OpenAPI document. File is invalid YAML or JSON:\n${error.message}`);
  }
}
```
Noting that at this point, the filePath is actually the response.data from an axios.get.

**Comment by rwalle61** [comment]
Cool, so that's the behaviour we're aiming for. I agree that if we do option 1 we don't need to write out the file itself.

**Comment by rwalle61** [comment]
I am having trouble making sync calls with sync-request or syncrequest. 

When you say
>I made an sync axios.get to get the spec content


Is your `axios.get` sync or async? I thought axios could only do async. If you can make a sync call, can you post an example here?

**Comment by rwalle61** [comment]
Re my trouble making sync calls: for some reason both [sync-request](https://www.npmjs.com/package/sync-request) and [syncrequest](https://www.npmjs.com/package/syncrequest) hang when I try to make a sync call. This may be because they spawn separate processes to make the async call sync. I don't know enough about that to get it working.

The only other alternative is [http-sync](https://www.npmjs.com/package/http-sync), which seems to require us or users to install libcurl, which complicates things. Also it [may not work on Windows](https://github.com/ForbesLindesay/sync-request/issues/4#issuecomment-146649598).

Further, none of these 3 packages have active contributors.

Therefore it looks like we can't make sync calls, so option 1 is not possible. I still think option 2 (changing how users `require` our package, by making it async) is not worth the value of this feature. So I'm tempted to close this, and users wanting this feature can follow the simple code pattern described above. @GSDTN what do you think?

**Comment by rwalle61** [comment]
@GSDTN sorry I missed what you meant about 
> Another option is to not write to a file at all.

Would you be happy if you could do:
```js
before(async() => {
    const apiSpec = (await axios.get('url/to/openapi/spec')).data;
    // chai.use(chaiResponseValidator(apiSpec));
}
```
?

i.e. users wanting this feature will still have to get the openapi data themselves, but will not have to write out to a file.

**Comment by rwalle61** [comment]
I have published the ability to define API specs as objects under 0.6.0. https://github.com/RuntimeTools/chai-openapi-response-validator/releases/tag/0.6.0

Until we are able to make sync requests, I think we should leave this feature (ability to define API specs as URLs) for now

**Comment by rwalle61** [comment]
Reopen if anyone has further thoughts :)

**Comment by GSDTN** [comment]
I have been on vacation the last 3 weeks.  I think your approach below would work fine.

What I meant was that you could have the content – as you have below and directly feed it into the validator without the need to write to file.
