### ISSUE TITLE
Empty response body validation fails (null vs. empty string)

### ISSUE THREAD

**Issue by martnst** [RuntimeTools/chai-openapi-response-validator#54]
**OpenAPI version**
3

**Describe the bug**
Validation fails on 204 response, which has empty string as body. 

We are using [axios](https://github.com/axios/axios) for making the requests. 

**Expected behavior**
Test should pass with falsy body. 

**Additional context**

OpenAPI Spec: 
```
openapi: 3.0.0
info:
  version: "1.0"
  title: sample-backend
servers:
  - url: "http://localhost:8080"
paths:
  /users/{id}:
    delete: 
      tags:
        - users
      summary: "Deletes an user identified by the given id"
      parameters:
        - name: "id"
          example: "S9RgCx"
          in: path
          description: id to identify the entity
          required: true
          schema:
            type: string
      responses:
         "204":
          description: "Entity successfully deleted"    
```

Test Logs:
```
  0 passing (63ms)
  1 failing

  1) users crud operations
       delete an user
         should be deleted:
     AssertionError: expected res to satisfy API spec:
{
  message: 'The response was not valid.',
  errors: [
    {
      errorCode: 'type.openapi.responseValidation',
      message: 'response should be null'
    }
  ],
  actualResponse: { status: 204, body: '' }
}
      at Context.<anonymous> (tests/users.test.js:72:32)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**Comment by rwalle61** [comment]
Thanks for raising this, I’m on my phone but will look in more depth as soon as I can (next few days).

My first thoughts are:

Arguably, 204 should return no content, not even '', so we are validating correctly. However, if axios (and other request packages) is returning '' even when the server is set up correctly, then I agree it makes sense for us to treat '' as null in 204 cases.

So I would probably add a 204 to our test server and test that each request module in `differentRequestModules` behaves as we want. 

I think the fix will be minor, in maybe the Response.js class

Happy to take a PR, we’re at 100% test coverage and mutation score so the change will be safe. Otherwise I will do this when I have time (maybe next week)

**Comment by rwalle61** [comment]
I have looked at what each request module returns if in Express you do `res.sendStatus(204)`. I agree this is a bug, and I have a fix. Just tidying it now

**Comment by rwalle61** [comment]
PR is up https://github.com/RuntimeTools/chai-openapi-response-validator/pull/59

Would you like to pull that branch and try it out, or shall I just do an npm release?

**Comment by martnst** [comment]
Hi @rwalle61, thanks for the fix. I tested it with our tests and works.
